### ISSUE TITLE
Error: listen EADDRINUSE :::4000

### ISSUE THREAD

**Issue by olegman** [lamo2k123/daemon-command-webpack-plugin#1]
Dude! My ass is on fire 🔥  Please fix this bug 🙏

**Comment by olegman** [comment]
I love you dude! ❤️🎉

**Comment by lamo2k123** [comment]
Use version 1.3.0 option `outResolve`.

`new DaemonCommandPlugin('start:dev', {
            outResolve : /app:server:info Listening on =>/
        })`
